---
title: "About"
output:
  html_document:
    includes:
      in_header: about-cover.html
---

**Research**

My [work](https://scholar.google.ca/citations?user=CrX15nAAAAAJ&hl=en) focuses on integrating existing data, particularly participatory science data, to conduct broad-scale conservation research. I have a strong background in spatial statistics, decision science, data integration, literature review and big data analysis, and my research spans local, hemispheric and global scales. My lab at the University of Manitoba will focus primarily on improving conservation planning in anthropogenically-modified spaces. Many of my current projects examine balancing the needs of grassland birds and agriculture in grassland habitats. 

**Background**

I completed my PhD at Carleton University in 2023 specializing in quantitative biodiversity conservation. The aim of my thesis research was to examine how advances in the use and integration of big datasets are crucial for conducting more effective conservation research and improving management decisions and outcomes. I completed my undergraduate studies at the University of Victoria in 2015, with a Bachelor of Science in Biology. In the past, I have worked on a wide variety of projects, including [captive breeding research](https://zoologistjones.wordpress.com/phenotypicplasticity/) in Australia, [pinniped cognitive and sensory ecology](https://www.marine-science-center.de/home-86.html) in Germany, and [coral reef restoration](https://www.diveagainstdebris.org/diver/save-cambodian-marine-life) in Cambodia. More recently I worked for the Conservation Officer Service in British Columbia preventing the spread of [aquatic invasive species](https://www2.gov.bc.ca/gov/content/invasive-mussels/invasive-mussel-defence-program), and volunteered on a number of bird monitoring and banding projects with [Birds Canada](https://www.birdscanada.org/) and [Wild Research](http://wildresearch.ca/).

### Contact Me

**Email**: adb299@cornell.edu
